Added write CSV functionality
adokter/vol2birdR pull request #30
Opened 2023-05-01 19:36 UTC by iskandari

- Copied libvol2bird from vol2bird
- Mirrored functionality from vol2bird to write vpts csv if .csv extension found

2023-05-02 08:06 UTC, peterdesmet commented
Nice! Is it possible to drop an example csv output of this function as a comment to this pull request? I can then test if it meets the specification of VPTS CSV.

2023-05-02 17:36 UTC, iskandari commented
@peterdesmet here is a sample [output](https://github.com/iskandari/vol2bird/commit/d36008d80c7518f9b9e58e9c29c5b4bb6ac05c17)

2023-05-03 08:49 UTC, peterdesmet commented
Thanks, I notice the following things:

1. Move the column `dbz` so columns have the order `gap,eta,dens,dbz,dbz_all`
2. Correct column name typo `radar_wavelenght` to `radar_wavelength`
3. 7 out of the 25 values in `dbz` are much higher than the expected max of 100 (up to 7,385.88)
4. `rcs` and `radar_wavelength` seem to have a false decimal precision of 6 (e.g. `10.710000`). Can this be avoided?
5. `source_file` paths should not be absolute (start with `/`), e.g. `/Users/alexandertedeschi/Documents/CLO/data_pvol/2017/05/04/KHGX/KHGX20170504_013934_V06`. @adokter should we continue to warn for this?
6. 14 out of the 25 values in `dens` are lower than the expected minimum of 0 (up to -29.92)

2023-05-03 15:13 UTC, adokter commented
>  `source_file` paths should not be absolute (start with `/`), e.g. `/Users/alexandertedeschi/Documents/CLO/data_pvol/2017/05/04/KHGX/KHGX20170504_013934_V06`. @adokter should we continue to warn for this?

@peterdesmet  - so when source refers to a local file, we use only the base name, and when it refers to an s3 bucket we give the full path? Long paths like this do increase the file size quite a bit, so agree that just the filename when dealing with a locally processed file is better

2023-05-04 16:16 UTC, adokter commented
Several of the columns are mixed up, e.g. what is labeled `dbz` is actually `eta`, which is why the validation by @peterdesmet failed

2023-05-05 08:38 UTC, peterdesmet commented
> .. what should be the precision required for `rcs`? I was looking at the min constraint `minimum: 1e-15`

That is the minimum because it should not be 0. The precision can be the one defined vol2bird. I've only seen integer values, like `11`.

2023-05-05 15:03 UTC, adokter requested changes

2023-05-05 15:03 UTC, adokter commented on src/libvol2bird/libvol2bird.c
> +char* get_radar_name(char* source) {
change to `int get_radar_name(char* source, char* radarName)`, copying radar name from source into misc.radarName field. Output int can indicate of copy was succesful

2023-05-05 21:07 UTC, merged

2023-05-06 08:38 UTC, peterdesmet commented
Is it possible to post a new `output.csv` here in a comment, so I can validate it?

2023-05-08 15:56 UTC, iskandari commented
@peterdesmet since `rcs` can theoretically be a very small number, I don't enforce precision and instead remove trailing zeroes.

> > .. what should be the precision required for `rcs`? I was looking at the min constraint `minimum: 1e-15`
> 
> That is the minimum because it should not be 0. The precision can be the one defined vol2bird. I've only seen integer values, like `11`.